theme: jekyll-theme-cayman
title: Progressive Multi-Scale Light Field Networks
description: '<div style="display: flex; flex-direction: row; color: #FFF; flex-wrap: wrap;">
<a href="https://davidl.me" style="margin-left:1rem; flex-grow: 1; color: #FFF;">David Li</a>
<a href="http://www.cs.umd.edu/~varshney/" style="margin-left:1rem; flex-grow: 1; color: #FFF;">Amitabh Varshney</a>
</div>
<p style="margin-bottom: -3rem;">
<a href="https://3dvconf.github.io/2022/" style="color: #FFF;">2022 International Conference on 3D Vision (3DV 2022)</a>
</p>'
github:
  is_project_page: false